import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";
import aspectRatio from "@tailwindcss/aspect-ratio";
import animate from "tailwindcss-animate";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        display: ['"DM Sans"', "system-ui", "sans-serif"],
        sans: ['"Inter"', "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      colors: {
        // Brand
        brand: {
          DEFAULT: "#FF5100",
          50: "#FFF4ED",
          100: "#FFE6D5",
          200: "#FECCAA",
          300: "#FDAA74",
          400: "#FC823D",
          500: "#FF5100",
          600: "#E93D00",
          700: "#C42E00",
          800: "#9E2600",
          900: "#802200",
          950: "#461200",
        },
        navy: {
          DEFAULT: "#1E232A",
          50: "#F4F5F7",
          100: "#E3E6EB",
          200: "#C7CCD6",
          300: "#9BA3B2",
          400: "#6B7280",
          500: "#4B5261",
          600: "#373D48",
          700: "#1E232A",
          800: "#171B20",
          900: "#0F1117",
          950: "#0A0C0F",
        },
        // Semantic
        success: {
          DEFAULT: "#1DB954",
          50: "#ECFDF5",
          100: "#D1FAE5",
          500: "#1DB954",
          600: "#16A34A",
          700: "#15803D",
          900: "#064E3B",
          950: "#022C22",
        },
        warning: {
          DEFAULT: "#FFC107",
          50: "#FFFBEB",
          100: "#FEF3C7",
          500: "#FFC107",
          600: "#D97706",
          700: "#B45309",
          900: "#78350F",
          950: "#451A03",
        },
        danger: {
          DEFAULT: "#E53935",
          50: "#FEF2F2",
          100: "#FEE2E2",
          500: "#E53935",
          600: "#DC2626",
          700: "#B91C1C",
          900: "#7F1D1D",
          950: "#450A0A",
        },
        // Surface system
        surface: "var(--color-surface)",
        "surface-muted": "var(--color-surface-muted)",
        "surface-hover": "var(--color-surface-hover)",
        ink: "var(--color-ink)",
        muted: "var(--color-muted)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        border: "var(--color-border)",
        card: "var(--color-card)",
        "card-hover": "var(--color-card-hover)",
        heading: "var(--color-heading)",
        body: "var(--color-body)",
      },
      fontSize: {
        "2xs": ["0.75rem", { lineHeight: "1rem" }],
        xs: ["0.8125rem", { lineHeight: "1.25rem" }],
        sm: ["0.875rem", { lineHeight: "1.5" }],
        base: ["1rem", { lineHeight: "1.5" }],
        lg: ["1.125rem", { lineHeight: "1.5" }],
        xl: ["1.25rem", { lineHeight: "1.5" }],
        "2xl": ["1.5rem", { lineHeight: "1.2" }],
        "3xl": ["1.875rem", { lineHeight: "1.2" }],
        "4xl": ["2.25rem", { lineHeight: "1.2" }],
        "5xl": ["3rem", { lineHeight: "1.1" }],
        "6xl": ["3.5rem", { lineHeight: "1.1" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.375rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(15, 23, 42, 0.04)",
        sm: "0 1px 3px rgba(15, 23, 42, 0.08), 0 1px 2px rgba(15, 23, 42, 0.04)",
        soft: "0 1px 2px rgba(15, 23, 42, 0.04), 0 8px 24px rgba(15, 23, 42, 0.06)",
        lift: "0 16px 40px rgba(15, 23, 42, 0.12)",
        glow: "0 0 20px rgba(255, 81, 0, 0.25)",
        "glow-lg": "0 0 40px rgba(255, 81, 0, 0.15), 0 0 80px rgba(255, 81, 0, 0.08)",
      },
      transitionTimingFunction: {
        ui: "cubic-bezier(0.23, 1, 0.32, 1)",
      },
      spacing: {
        18: "4.5rem",
        88: "22rem",
        128: "32rem",
      },
      animation: {
        "fade-in": "fadeIn 200ms ease-out",
        "fade-out": "fadeOut 200ms ease-out",
        "slide-up": "slideUp 200ms ease-out",
        "slide-down": "slideDown 200ms ease-out",
        "slide-in-right": "slideInRight 200ms ease-out",
        "slide-out-right": "slideOutRight 200ms ease-out",
        "scale-in": "scaleIn 300ms cubic-bezier(0.34, 1.56, 0.64, 1)",
        "scale-out": "scaleOut 200ms ease-out",
        "bounce-in": "bounceIn 350ms cubic-bezier(0.34, 1.56, 0.64, 1)",
        shimmer: "shimmer 1.5s linear infinite",
        marquee: "marquee 40s linear infinite",
        marquee2: "marquee2 40s linear infinite",
        "pulse-dot": "pulseDot 2s ease-in-out infinite",
        "float": "float 6s ease-in-out infinite",
        "typewriter": "typewriter 0.6s steps(20) forwards",
        "page-enter": "pageEnter 200ms ease-out",
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeOut: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          from: { opacity: "0", transform: "translateY(-8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          from: { opacity: "0", transform: "translateX(16px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        slideOutRight: {
          from: { opacity: "1", transform: "translateX(0)" },
          to: { opacity: "0", transform: "translateX(16px)" },
        },
        scaleIn: {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        scaleOut: {
          from: { opacity: "1", transform: "scale(1)" },
          to: { opacity: "0", transform: "scale(0.95)" },
        },
        bounceIn: {
          "0%": { opacity: "0", transform: "scale(0.3)" },
          "50%": { transform: "scale(1.05)" },
          "70%": { transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          from: { backgroundPosition: "200% 0" },
          to: { backgroundPosition: "-200% 0" },
        },
        marquee: {
          from: { transform: "translateX(0%)" },
          to: { transform: "translateX(-100%)" },
        },
        marquee2: {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0%)" },
        },
        pulseDot: {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.5", transform: "scale(1.5)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        typewriter: {
          from: { width: "0" },
          to: { width: "100%" },
        },
        pageEnter: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "hero-gradient": "linear-gradient(135deg, #FF5100 0%, #FF8533 50%, #FF5100 100%)",
        "dark-gradient": "linear-gradient(180deg, #0F1117 0%, #1E232A 100%)",
      },
      maxWidth: {
        "8xl": "88rem",
      },
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
  },
  plugins: [forms, typography, aspectRatio, animate],
};
